function Hd = filterdesign_using_fdatool
%FILTERDESIGN_USING_FDATOOL Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 16-Aug-2021 22:14:34

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 173.6;  % Sampling Frequency

Fstop1 = 7;      % First Stopband Frequency
Fpass1 = 8;      % First Passband Frequency
Fpass2 = 12;     % Second Passband Frequency
Fstop2 = 13;     % Second Stopband Frequency
Dstop1 = 0.001;  % First Stopband Attenuation
Dpass  = 0.1;    % Passband Ripple
Dstop2 = 0.001;  % Second Stopband Attenuation
dens   = 20;     % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
